import esbuild from 'esbuild';
import process from 'process';
import path from 'node:path';
import { builtinModules } from 'node:module';
import { readFileSync } from 'node:fs';
import { spawn } from 'node:child_process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const manifest = JSON.parse(readFileSync('manifest.json', 'utf-8'));
const manifestId = manifest.id;

/**
 * Reloads the plugin in a running Obsidian instance via the `obsidian` CLI
 * after each successful dev/watch rebuild. Fire-and-forget: never throws or
 * blocks the watch loop, and only runs outside of production builds.
 */
const reloadPlugin = {
	name: 'reload-obsidian-plugin',
	setup(build) {
		build.onEnd((result) => {
			if (prod || result.errors.length > 0) {
				return;
			}
			const child = spawn('obsidian', [`plugin:reload`, `id=${manifestId}`], {
				stdio: 'ignore',
			});
			child.on('error', (err) => {
				console.warn(`[dev] Could not reload plugin in Obsidian: ${err.message}`);
			});
			child.on('exit', (code) => {
				if (code !== 0) {
					console.warn(
						`[dev] Could not reload plugin in Obsidian: obsidian CLI exited with code ${code}`,
					);
				}
			});
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		// Node builtins under both specifier forms — `builtinModules` lists
		// only the unprefixed names, but source imports use `node:` prefixes
		// (e.g. `node:crypto` in the persistence adapter helpers).
		...builtinModules,
		...builtinModules.map((name) => `node:${name}`),
	],
	format: 'cjs',
	target: 'es2022',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	define: {
		__DEV__: JSON.stringify(!prod),
	},
	alias: {
		// Mirrors the `@core/*` and `@ports/*` path aliases in tsconfig.json
		// so these imports resolve at bundle time, not just at type-check
		// time.
		'@core': path.resolve(process.cwd(), 'src/core'),
		'@ports': path.resolve(process.cwd(), 'src/ports'),
	},
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [reloadPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
